version: '3'

services:
  database:
      image: 'bitnami/postgresql'
      ports:
        - '5432:5432'
      environment:
        - POSTGRESQL_USERNAME=gateway
        - POSTGRESQL_PASSWORD=gateway
        - POSTGRESQL_DATABASE=gateway_db
      volumes:
        - 'postgresql_data:/bitnami/postgresql' # for data persistence

  api-gateway:
    image: node:lts-bullseye-slim
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://gateway:gateway@database:5432/gateway_db
    command: yarn start
    ports:
      - 5000:5000
    working_dir: /usr/src/gateway
    volumes:
      - ./:/usr/src/gateway

  test_database:
    image: 'bitnami/postgresql'
    ports:
      - '5433:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=test
    volumes:
      - 'test_postgresql_data:/bitnami/postgresql'


volumes:
  postgresql_data:
    driver: local

  test_postgresql_data:
    driver: local
