version: '3'

services:
  database:
      image: 'bitnami/postgresql'
      ports:
        - '5432:5432'
      environment:
        - POSTGRESQL_USERNAME=gateway
        - POSTGRESQL_PASSWORD=gateway
        - POSTGRESQL_DATABASE=gateway_db
      volumes:
        - 'postgresql_data:/bitnami/postgresql' # for data persistence

  api-gateway:
    image: node:lts-bullseye-slim
    depends_on:
      - database
    command: yarn start
    ports:
      - 5000:5000
    working_dir: /usr/src/gateway
    volumes:
      - ./:/usr/src/gateway


volumes:
  postgresql_data:
    driver: local
